### ISSUE TITLE
Solidus Marketplace Roadmap

### ISSUE THREAD

**Issue by dhonig** [boomerdigital/solidus_marketplace#1]
Boomer.digital will be sponsoring development of a re-development of Spree_Marketplace.

Why are we going to redevelop this extension, isn't the old one good enough?
- The old one is split amongst two extensions, spree_dropship and spree_marketplace.  Most of the functionality is in spree_dropship with spree_marketplace not adding signifigant concerns beyond payments.
- We want to create a fully modern extension that directly refllects the needs of marketplace customers in 2016 and beyond.
- We want to develop cleanly against the latest version of Solidus.io and leverage all of the improvements without having to compensate for past Spree versions and changes.
- Our roadmap will have a much richer set of features.

We would love feedback on the following features:
 -Suppliers -Provide the ability to have one or more suppliers in the marketplace.
 -Supplier Portal - Provide suppliers with a comprehensive dashboard/admin interface allowing them to manage their relationship with the marketplace.
  -Payment Methods - Payment methods will be determined by the market maker.  So if the market maker chooses to support Paypal and Stripe.  
 -Drop Shipping - We will support equivalent functionality to spree_dropship. Do we need to include support for multiple  warehouses etc. on a supplier level?

**Comment by dhonig** [comment]
cc: @mtomov  @thaume  would love to get your input.  Then we can prioritize features and kickoff development.

**Comment by thaume** [comment]
Hey @dhonig !

This roadmap sketch sounds great. I particularly like the idea of centralised payment methods (vs each supplier has its own PSP), and a strong providers management (with maybe a couple of users per provider with different rights). I guess those are the two most important features in my opinion. Regarding drop shipping, supporting multiple warehouses would make a lot of sense on a supplier level.

**Comment by Stevo-S** [comment]
Hi @dhonig 

I just want to express my interest in this extension. I am just trying out Solidus and it would
be great if it was easy to to turn a solidus app into a marketplace.
The spree_marketplace extension doesn't look like it's being actively maintained so it would
be cool if this extension really got some traction.

I don't have much experience with Ruby on Rails or e-commerce but I am willing to help in any
way I can (for what its worth).

**Comment by dhonig** [comment]
@mtomov and I need to get a convincing start on it.  The project we were
planning to use it on is going live without it but will need it soon.....
_promise_ I'll write up the entire roadmap this week and post it
up.....then we can divide and conquer?

**Comment by Stevo-S** [comment]
Awesome!
Divide and conquer. Sounds like a plan.
Looking forward to it.

**Comment by KazKazar** [comment]
Hello, 
I would like to participate in this project.
I don't have much experience in Rails but I have a lot of motivation... :)

**Comment by dhonig** [comment]
Hey everyone can you please list your top features for myself and @mtomov  we have been delayed but are soon getting to a place where we can pick this up again.

I have distilled what we have so far into a mindmap that I will keep updating:
We are going to be meeting internally next week to finalize a direction on this.  I would appreicate everyone's feedback, I have started assembling features in this mind map: 
https://www.mindmeister.com/711100144/solidus-marketplace 

I will update the mindmap with all comments on this thread to try to get a complete feature set.  We will meet internally next week to kick this off internally.  Then I'd love to schedule a google hangout.  We would love to have others collaborate on this why we build it.  As the first one was built more or less in a Vacuum for one client.

**Comment by dhonig** [comment]
We are going to be meeting internally next week to finalize a direction on this.  I would appreicate everyone's feedback, I have started assembling features in this mind map: 
https://www.mindmeister.com/711100144/solidus-marketplace 

I will update with all of the comments left on this thread

**Comment by thaume** [comment]
Hey @dhonig great work on the first draft of the roadmap. Let us know once you've had your meeting with Martin :)

**Comment by dromanoBD** [comment]
Suggested enhancements to the requirements above:
-Suppliers -Provide the ability to have one or more suppliers in the marketplace.
Dana: Provide the ability to the supplier to promote the items they've contributed to the marketplace to amplify marketing through social sharing with trackable links
-Supplier Portal - Provide suppliers with a comprehensive dashboard/admin interface allowing them to manage their relationship with the marketplace, 
Dana: including views, favorites, orders, best performing products, most searched for items

Marketplace shipping- will this allow both scenarios: a supplier to drop ship to the customer or for the marketplace owner to ship product. 
use case 1: a marketplace like "Etsy" is created where producers are creating and shipping their own product direct to consumer
use case 2: a marketplace like "CafePress" where a producer uploads their design but CafePress handles printing/order fulfillment and shipping

**Comment by KazKazar** [comment]
Hi, the roadmap looks great.
I have found some lists of marketplace features, they are very detailed and I think can be very useful for our project. Please check the link and let me know what you think.
https://realtimeboard.com/app/board/o9J_k0nFr9w=/

**Comment by mtomov** [comment]
Hello,

I've reviewed the present state of the [_spree_drop_ship_](https://github.com/spree-contrib/spree_drop_ship) extension and I think that it will be a good starting point for starting this marketplace extension, as judging by the commit history, Jeff & contributors have spent quite some effort on it - thank you! As we probably won't need to maintain backwards compatibility with it, we can make any design changes in the beginning, but having it as a foundation & initial direction is just great. 

So, the overall plan is as follows:

#### Part 1 - set-up the codebase
1. Fork [spree_drop_ship](https://github.com/spree-contrib/spree_drop_ship) - master branch
2. Merge https://github.com/spree-contrib/spree_drop_ship/pull/78, as it contains important fixes
3. Cherry-pick this commit for additional small fixes - https://github.com/ronzalo/spree_drop_ship/commit/3540c7b3be507f97c12afab5bf28e701234eb004
4. Convert to Solidus using this https://github.com/ronzalo/spree_drop_ship/commit/ef268205272fdc2cbf5ab4ec826090c2cfa1e350 as a base. Thanks @ronzalo!

#### Part 2 - Re-consider the data model.

The following relationships are currently established:
- a Supplier _has many_ Users associated with it
- a Supplier _has many_ Stock Locations
- a Variant _has many_  Suppliers through an intermediate table _spree_supplier_variants_
- a Shipment _has many_ payments - [read more about this](https://github.com/spree-contrib/spree_drop_ship/blob/master/README.md#upgrading)

This kind of model (Variant _has many_  Suppliers) allows for a marketplace like Amazon - where a product (variant) is stocked by more than one vendor (supplier). A simpler model could be:
- a Product _has one_ supplier - this is in the likes of eBay

The more complicated model (Variant _has many_ Suppliers) requires in addition to implement:
- supplier preference - which supplier's stock is to be consumed first
- UI for assigning a variant to more than one supplier
- splitting shipments (packages) based on supplier - I think this is already there.
- creating proper permissions for suppliers to change the details of the same product - or will the marketplace owner do that?

So, **question 1)**: Should we maybe simplify the model relationship between products and suppliers to only allow each supplier to maintain their own set of products? (like eBay)

## 

If we stick to the Variant _has many_ relationship, we need to solve the following:

Currently, there's 2 routes to get from a Variant to its Supplier:
1. a Variant _has many_  Suppliers through this table _spree_supplier_variants_  (added by the drop ship extension)
2. a Variant _has many_ Stock Items, which in turn have one Stock Location, which in turn has one Supplier (only the Stock Location <-> Supplier bit is added by the extension)

So, the relationship between a Variant and Supplier is established twice, the difference being one table lookup more in the second case. 

So, **question 2)**: If we are to keep the model of a Variant _has many_ Suppliers (like Amazon), do we maybe not want to refactor the code to remove this duplication and leave only the Stock Item route to get to a Supplier?

#### Part 3 - Evaluate the user interface / flows
1. Supplier profile - create/edit. Have to find out if users can create supplier profiles themselves, or the marketplace admin does and manages those. I guess the former is better?
2. Manage shipments - suppliers can manage the shipments on their own (can Ship, maybe change the tracking URL). There's a UI for that, have to check how it looks like.
3. Drop ship settings - an admin settings panel

_I will be doing more research here, and will add screenshots of the current UI flow._

**Question 3** - Apart from those 3 - what additional UI flows to you think are needed?

#### Part 4 - Email communication
1. [Supplier Welcome](https://github.com/spree-contrib/spree_drop_ship/blob/master/app/views/spree/supplier_mailer/welcome.html.erb) - email sent when a new supplier is registered.
2. [Supplier Order](https://github.com/spree-contrib/spree_drop_ship/blob/master/app/views/spree/drop_ship_order_mailer/supplier_order.html.erb) - details of a new Shipment from a completed order are sent to the Supplier for them to act upon

#### Part 5 - Payments
1. [Spree Marketplace](https://github.com/spree-contrib/spree_marketplace) does handle payments with Stripe.
   - will have to understand how it all works
2. [Sharetribe](http://sharetribe.com/), which is also [open source](https://github.com/sharetribe/sharetribe) - does handle payments with Braintree and PayPal using the [Braintree Marketplace](https://www.braintreepayments.com/products-and-features/marketplace)

Ideally we would be able to somehow abstract both in a common interface, and allow the marketplace owner to choose which one to do. I guess we can start even with one of them, given that there's a commonly abstracted interface.

**Q4**: Do you see it worthwhile to keep the payments section in its own extension, as Spree marketplace does? Has anyone got experience with that to share if it is more trouble, or it might actually make it easier if Drop Ship and the Payments (marketplace) are separate?

#### Part 6 - Consider supported scenarios

We need to come up with a few common marketplace scenarios and see how the system to be developed will handle those. Looking at the [Success stories at Sharetribe](https://www.sharetribe.com/stories.html) can be a good start. One particular feature that I really like out of Sharetribe was the ability to rent. I think this is a very common scenario for marketplace - creating availability of people and objects / places, say a marketplace for nannies, baby-sitters, etc ..

I will leave this section to you : )

---

Lastly, I will ping a few people that I have seen had something to do with a drop_ship/marketplace. Please unsubscribe if you are not interested, and sorry for the bother.

@JDutil  @ronzalo @alexmirk @isetarow @mattfran @grmahesh @dgross881 @fisherman818 @blacktea3937 @goodmaizi @yf6 @korki @sunny2601 @firman @pjar @damson @Ahmed--Mohsen @van5150 @silvanito @alric-m @benoitr @priviterag

**Comment by 4dandies** [comment]
Any update on release date?

**Comment by frankie-loves-jesus** [comment]
@mtomov, @dhonig any updates? This would without doubt be the ultimate Solidus extension, at least for those of us in the startup phase who can't afford to buy inventory.

**Comment by mtomov** [comment]
Hello, I haven't progressed this further than what is stated in the above comment. A big problem for me was the lack of use case scenarios through which the required features can be defined.

**Comment by frankie-loves-jesus** [comment]
Isn't dropshipping and a marketplace two different things?

Ie. dropshipping being where the store owner handpicks his or her suppliers, adds their products manually or batch import via an API, and then emails them / forwards payment whenever orders are made. Here the suppliers should brand the packaging to make it look like it came from the store. As far as the customer is concerned, the supplier is non-existent. Customer service, returns etc. are handled by the store.

A marketplace would be where suppliers themselves seek out and join as members, with their own profile page / control panel, using the traction of the marketplace to get their products sold. Here the marketplace would also email / forward payments (minus a tiny commission) to the supplier, who keeps his or her brand intact with regards to packaging. In other words, the marketplace only helps facilitate the purchase, while the supplier would have to deal with customer service, returns etc. on their own.

I hope I got it all right. I also hope that, in addition to Boomer Digital funding, you manage to find the inspiration to get this show on the road.

**Comment by dhonig** [comment]
@frankie-loves-jesus  if you can help us agree on a minimal feature set then this is something we can continue to work on.   We are happy to lead the way here, but our original use case for this was deferred indefinitely....So we really need some community involvement to make sure this is something people really need and can use.

**Comment by frankie-loves-jesus** [comment]
Absolutely, where do we start?

**Comment by dhonig** [comment]
In this entire group on this ticket, no one responded with feedback @mtomov's request for comments on his omnibus post.  If we could start there and identify the minimum features to get started on, then I think @mtomov  would be happy to pick this up

**Comment by frankie-loves-jesus** [comment]
Perhaps it would be better to first port spree_drop_ship and spree_marketplace to Solidus, and from there decide what we need to add / remove?

I think the likelihood of getting community support would increase greatly once these plugs are listed in the Solidus extensions page.

**Comment by dhonig** [comment]
@frankie-loves-jesus  the mandate here was to not adopt all of the technical debt.  To not mix drop shipping with marketplace.  To instead do something that would make spree/solidus comeptitive with products such as Iceberg labs.  This is no comment on the work previously done, but rather a realization that we should start out without inheriting technical debt and design something suited for customer needs.  I think the simplest thing to continue with this is to agree on the 5 most important feature and then we can schedule time for Martin to implement them.   Once we have that shell, we can get this listed on the extension list.

http://www.izberg-marketplace.com/

**Comment by 4dandies** [comment]
To implementing a marketplace, Rails community already have Sharetribe project.
I think what Solidus needs, for people in a startup phase, is a gem that automatically process the process of drop shipping.
I think the features that we look are something like:
Administrator:
- Register suppliers with the common information (address, contacts, VAT number, etc).
- Add products should have a option to choose the supplier. I Think 1:1 is the way to go. (I think people will not have multiple suppliers for the same product, otherwise is a marketplace).

Supplier:
- Receive invoice (customer information, product information, etc) via email after an order. (Customer should make orders with products from different suppliers. So the invoice sent to the supplier should have only the products of the supplier.)
- Possibility to change the inventory.
- Add tracking information to an order.
- Control panel with orders and reports. (not priority).

The owner of store controls everything (products, price, payments), and allow suppliers to agile the process of reporting information about orders and inventory.

All business related tasks, like pay the products to the supplier, return process, should be done by the company and not by Solidus.

**Comment by mtomov** [comment]
@4dandies that's a very constructive comment, and very well said about Sharetrive already being there. Thanks!

**Comment by dhonig** [comment]
I think there is just about enough to get started on with those features.  I am aware of Sharetribe, but I think the use case and customer for this is not to plug into sharetribe, its to replace it entirely?

**Comment by sechix** [comment]
Hello, I am new in spree commerce, and I have choosen solidus in order to start my platform. I need marketplace extension, but I haven't found in the github yet. When will be realease? I can use spree_drop_ship stead? because when I try to install spree_drop_ship in solidus give me an error.
Thanks a lot !!!!!

**Comment by rlasch** [comment]
Does anyone know if any work on this has been started or not?

**Comment by mtomov** [comment]
No significant progress has been made at this point, sorry, but we might have an upcoming client who's interested in such a solution, so contributions will certainly be made.

_edited_

**Comment by rlasch** [comment]
I'm doing work for a client, and I'm giving serious consideration to Solidus.  The only thing that is missing is being able to track different suppliers against products/product variants.  For our needs, the simpler relationship where one product has one supplier is more in line with what we want AFAIK.  In your estimation @mtomov , how big of a project is this converting this over given the simpler relationship?  (Just looking for a quick guess.)

**Comment by mtomov** [comment]
Right, I had the conversion to Solidus almost completed on this one, but was missing the exact data modelling part to continue on it.

Now that you have a concrete requirement, that places a chip the basket for the simpler relationship of 1 product 1 supplier, which is the goal of this discussion.

If your question is on converting vs starting from scratch, I wouldn't say there's much of a difference, as either way we want to arrive at something re-usable, which we can invest in, and there's no backwards compatibility to consider.

So, maybe an idea would be that I push some code out, and you can have a look if you would be interested in then starting from there to arrive at a solution, which matches your business requirements. I can be reviewing the code and all.

_edit_: It seems that I have already pushed all progress made, and as you will notice by the [latest commit](https://github.com/boomerdigital/solidus_marketplace/commit/8e88e6fd509eca5b9bbf6cd087a1a41df9ab04a5) I have started exactly on the direction of 1 product -> 1 supplier

**Comment by rlasch** [comment]
Ok, then I'll pick this up and work with it a bit to see if I can use it for my needs.

**Comment by rlasch** [comment]
So I thought I would update my progress.  I am using solidus marketplace with solidus and solidus gateway for our store.  I have an importer in place that imports products into the store.  The part that I'm not sure of is where to get the payment finalized and where to finalize the shipment.  The moment that the payment is created and authorized, I really want to launch a job to send the order to our supplier, then finalize the payment.  I'm just not sure where to anchor it.  @mtomov do you have any thoughts on this?

Once I get this all working completely, I'll commit my changes and push a PR up.

**Comment by mtomov** [comment]
Well, I think there were even some regulations in the EU, which mandated that payment be taken at the point of goods shipment (I think that someone on the [Solidus slack](https://solidusio.slack.com/messages/solidus/) had explained it in more detail), so I guess if you have the "ship" event, you could do it there, or if it's difficult there - can be done earlier - as you said at the point you are launching the job. Good one with the jobs though!

**Comment by priom** [comment]
Anybody building dropship eCommerce with solidus and rails 5?

**Comment by kenton** [comment]
Closing this issue, as most of this has been captured in the [Roadmap page](https://github.com/boomerdigital/solidus_marketplace/wiki/Solidus-Marketplace-Roadmap-to-MVP) in the project wiki:
