### ISSUE TITLE
Could not find gem 'solidus_marketplace' in any of the gem sources

### ISSUE THREAD

**Issue by joao-j-souza** [boomerdigital/solidus_marketplace#3]
Hi,

I put this gem in gemfile but, when I try to run bundle install I got the error msg bellow...
Could not find gem 'solidus_marketplace' in any of the gem sources

**Comment by dhonig** [comment]
We are just getting started!  More to come!

**Comment by 4dandies** [comment]
Any update on release date?

**Comment by sechix** [comment]
For me the same error :( It is not ready yet? Thanks !!!!

**Comment by kenton** [comment]
Quick update to this ticket...

The initial version of this gem is published to rubygems now:
https://rubygems.org/gems/solidus_marketplace

You should be able to `gem install solidus_marketplace` or add that to your Gemfile and be good to go.

Check out the README for install instructions, etc:
https://github.com/boomerdigital/solidus_marketplace

If you play around with this and notice anything odd, add an issue to the Github Issues list.

Thanks

Closing this ticket as this message should resolve it.
