### ISSUE TITLE
I want to install this gem and test it

### ISSUE THREAD

**Issue by kainio** [boomerdigital/solidus_marketplace#5]
I know that this gem isn't ready, but I want to test it and see if I can contribute to it, I tried to install it but I couldn't, this project seems to be not active, I am interested in solidus and I am trying to build marketplace on top of it, I am also interested on porting of spree_drop_ship to solidus, but I am lacking development experience in rails and solidus.

By the way did you merge spree_marketplace and spree_drop_ship in one project ?

I want also know How I can start contributing to the project ?

**Comment by kainio** [comment]
How I can run the migrations ?

I added this repo to gemfile and ran `bundle install`

I ran `rails g spree_drop_ship:install` but it didn't copy the migrations
`

**Comment by pmn4** [comment]
@kainio this repo is coming back to life... @kenton is in the process of ticketing up all of the work that needs to be done, so work should begin shortly.
Check out the [Slack channel](https://solidusio.slack.com/messages/C6G40U0JV) for more info

**Comment by hototoh** [comment]
Hi, I'm also trying to develop marketplace using solidus because spree dev seems finishing. I would like to know when you expect to release this MVP. Thanks.

**Comment by kenton** [comment]
Quick update to this ticket...

The initial version of this gem is published to rubygems now:
https://rubygems.org/gems/solidus_marketplace

You should be able to `gem install solidus_marketplace` or add that to your Gemfile and be good to go.

Check out the README for install instructions, etc:
https://github.com/boomerdigital/solidus_marketplace

If you play around with this and notice anything odd, add an issue to the Github Issues list.

Thanks

Closing this ticket as this message should resolve it.
